# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abrigo Patterns
email: brad.sosnowski@abrigo.com
description: # this means to ignore newlines until "baseurl:"
  Pattern library for Abrigo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://design.abrigo.com" # the base hostname & protocol for your site
github_username:  creativehamlet
logo_url: svg/min/logo.svg

collections:
 - icons

# Build settings
markdown: kramdown

# Inline svg dependent gems
gems:
  - jekyll-inline-svg

svg:
  optimize: true

# Excluded files/directories
exclude: [
    README.md,
    package.json,
    package-lock.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    _sass,
    css,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    svg,
    .DS_Store
]
keep_files: [
    css
]
