# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abrigo Patterns
email: brad.sosnowski@abrigo.com
description: > # this means to ignore newlines until "baseurl:"
  Pattern library for Abrigo.
baseurl: "/abrigo-patterns" # the subpath of your site, e.g. /blog
url: "http://abrigo.com" # the base hostname & protocol for your site
twitter_username: creativehamlet
github_username:  creativehamlet

# Build settings
markdown: kramdown

exclude: ['README.md', '/node_modules', 'css', '_sass', 'icons']
keep_files: ['css', 'icons']
